function [r0Tr1,r1Tr2,r2Tr3,r3Tr4,r4Tr5,r5Tr6] = mgdNed2(in1,in2)
%mgdNed2
%    [r0Tr1,r1Tr2,r2Tr3,r3Tr4,r4Tr5,r5Tr6] = mgdNed2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 15:59:47

a2 = in2(2,:);
a3 = in2(3,:);
d1 = in2(1,:);
d4 = in2(4,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = cos(q6);
t8 = sin(q1);
r0Tr1 = reshape([t2,t8,0.0,0.0,0.0,0.0,1.0,0.0,t8,-t2,0.0,0.0,d1.*t2,d1.*t8,0.0,1.0],[4,4]);
if nargout > 1
    t9 = sin(q2);
    t10 = sin(q3);
    t11 = sin(q4);
    t12 = sin(q5);
    t13 = sin(q6);
    t14 = -t9;
    r1Tr2 = reshape([t14,t3,0.0,0.0,-t3,t14,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,a2,1.0],[4,4]);
end
if nargout > 2
    r2Tr3 = reshape([t4,t10,0.0,0.0,0.0,0.0,1.0,0.0,t10,-t4,0.0,0.0,0.0,0.0,a3,1.0],[4,4]);
end
if nargout > 3
    r3Tr4 = reshape([t5,t11,0.0,0.0,0.0,0.0,-1.0,0.0,-t11,t5,0.0,0.0,d4.*t5,d4.*t11,0.0,1.0],[4,4]);
end
if nargout > 4
    r4Tr5 = reshape([t6,t12,0.0,0.0,0.0,0.0,1.0,0.0,t12,-t6,0.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
end
if nargout > 5
    r5Tr6 = reshape([t7,t13,0.0,0.0,-t13,t7,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
end
end
