function [X,Y,Z] = params_type2_O14_q1_(a2,a3,d4,q4,t14,t24)
%params_type2_O14_q1_
%    [X,Y,Z] = params_type2_O14_q1_(A2,A3,D4,Q4,T14,T24)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 15:59:48

X = t14;
if nargout > 1
    Y = -t24;
end
if nargout > 2
    Z = a2+a3+d4.*sin(q4);
end
end
