function var1 = vars_type2_O14_q1_(Ai)
%vars_type2_O14_q1_
%    VAR1 = vars_type2_O14_q1_(Ai)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 15:59:48

var1 = Ai;
end
