function [H1,Y1] = CalcHF(x,y,z,q1,q2,q3,q4,q5,q6,d1,d2,d3,d4,d5,d6,a2,a3)
%CALCHF
%    [H1,Y1] = CALCHF(X,Y,Z,Q1,Q2,Q3,Q4,Q5,Q6,D1,D2,D3,D4,D5,D6,A2,A3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    28-Nov-2023 18:22:46

H1 = reshape([x,0.0,0.0,y,0.0,0.0,z,0.0,0.0,1.0,0.0,0.0,0.0,x,0.0,0.0,y,0.0,0.0,z,0.0,0.0,1.0,0.0,0.0,0.0,x,0.0,0.0,y,0.0,0.0,z,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,15]);
if nargout > 1
    Y1 = [d4;pi.*(-1.0./2.0);-d1];
end
