function [X,Y,Z] = params_type2_T36_33_q5_(t33)
%params_type2_T36_33_q5_
%    [X,Y,Z] = params_type2_T36_33_q5_(T33)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 17:40:18

X = 0.0;
if nargout > 1
    Y = -1.0;
end
if nargout > 2
    Z = -t33;
end
end
