function [X,Y,Z] = params_type2_O14_q1_(t14,t24)
%params_type2_O14_q1_
%    [X,Y,Z] = params_type2_O14_q1_(T14,T24)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 18:02:18

X = t14;
if nargout > 1
    Y = -t24;
end
if nargout > 2
    Z = 0.0;
end
end
