function [X1,Y1,Z1,X2,Y2,Z2] = params_type3_T46_13_q4_(t14,t24)
%params_type3_T46_13_q4_
%    [X1,Y1,Z1,X2,Y2,Z2] = params_type3_T46_13_q4_(T14,T24)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 17:40:13

X1 = t24;
if nargout > 1
    Y1 = t14;
end
if nargout > 2
    Z1 = 0.0;
end
if nargout > 3
    X2 = -t14;
end
if nargout > 4
    Y2 = t24;
end
if nargout > 5
    Z2 = 0.0;
end
end
