function [X1,Y1,Z1,X2,Y2,Z2] = params_type3_T35_q6_(t31,t32,t34)
%params_type3_T35_q6_
%    [X1,Y1,Z1,X2,Y2,Z2] = params_type3_T35_q6_(T31,T32,T34)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 17:40:19

X1 = -t32;
if nargout > 1
    Y1 = t31;
end
if nargout > 2
    Z1 = 0.0;
end
if nargout > 3
    X2 = t31;
end
if nargout > 4
    Y2 = t32;
end
if nargout > 5
    Z2 = t34;
end
end
