function [W,X,Y,Z1,Z2] = params_type6_O24_q2_q3_(a2,d1,q1,t14,t24,t34)
%params_type6_O24_q2_q3_
%    [W,X,Y,Z1,Z2] = params_type6_O24_q2_q3_(A2,D1,Q1,T14,T24,T34)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 18:02:21

W = 0.0;
if nargout > 1
    X = -d1+t34;
end
if nargout > 2
    Y = -t14.*cos(q1)-t24.*sin(q1);
end
if nargout > 3
    Z1 = -a2;
end
if nargout > 4
    Z2 = 0.0;
end
end
