function var1 = vars_type3_T35_q6_(Ai)
%vars_type3_T35_q6_
%    VAR1 = vars_type3_T35_q6_(Ai)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 17:40:19

var1 = Ai;
end
