function [var1,var2] = vars_type6_O24_q2_q3_(Ai,Ak)
%vars_type6_O24_q2_q3_
%    [VAR1,VAR2] = vars_type6_O24_q2_q3_(Ai,Ak)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 18:02:21

var1 = Ai;
if nargout > 1
    var2 = Ak;
end
end
