function var1 = vars_type2_T36_33_q5_(Ai)
%vars_type2_T36_33_q5_
%    VAR1 = vars_type2_T36_33_q5_(Ai)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 17:40:18

var1 = Ai;
end
