function var1 = vars_type3_T46_q4_(Ai)
%vars_type3_T46_q4_
%    VAR1 = vars_type3_T46_q4_(Ai)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Dec-2023 17:16:07

var1 = Ai;
end
