function [T01,T12,T23,T34,T45,T56] = MGD_ur10(q1,q2,q3,q4,q5,q6,d1,a2,a3,d4,d5,d6)
%MGD_UR10
%    [T01,T12,T23,T34,T45,T56] = MGD_UR10(Q1,Q2,Q3,Q4,Q5,Q6,D1,A2,A3,D4,D5,D6)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Nov-2018 18:23:09

t2 = sin(q1);
t3 = cos(q1);
T01 = reshape([t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2,-t3,0.0,0.0,0.0,0.0,d1,1.0],[4,4]);
if nargout > 1
    t4 = cos(q2);
    t5 = sin(q2);
    T12 = reshape([t4,t5,0.0,0.0,-t5,t4,0.0,0.0,0.0,0.0,1.0,0.0,a2.*t4,a2.*t5,0.0,1.0],[4,4]);
end
if nargout > 2
    t6 = cos(q3);
    t7 = sin(q3);
    T23 = reshape([t6,t7,0.0,0.0,-t7,t6,0.0,0.0,0.0,0.0,1.0,0.0,a3.*t6,a3.*t7,0.0,1.0],[4,4]);
end
if nargout > 3
    t8 = sin(q4);
    t9 = cos(q4);
    T34 = reshape([t9,t8,0.0,0.0,0.0,0.0,1.0,0.0,t8,-t9,0.0,0.0,0.0,0.0,d4,1.0],[4,4]);
end
if nargout > 4
    t10 = sin(q5);
    t11 = cos(q5);
    T45 = reshape([t11,t10,0.0,0.0,0.0,0.0,1.0,0.0,t10,-t11,0.0,0.0,0.0,0.0,d5,1.0],[4,4]);
end
if nargout > 5
    t12 = sin(q6);
    t13 = cos(q6);
    T56 = reshape([t13,t12,0.0,0.0,-t12,t13,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,d6,1.0],[4,4]);
end
